name: GitHub Actions Demo
run-name: Build and Publish ${{ github.repository }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Build-and-Publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up dotnet 10.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'
          cache: true
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
        run: mkdir build
        run: powershell Compress-Archive -Path bin/Release/net10.0/* -DestinationPath build/release.zip
      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: build/release.zip
            asset_name: release.zip
            tag: ${{ github.ref }}
            overwrite: true
            body: "This is my release text"
